
# gp-gettext-setup.mk autogenerated by GP_GETTEXT_SETUP_INIT

distclean-local: distclean-local-gp-gettext-setup
.PHONY: distclean-local-gp-gettext-setup
distclean-local-gp-gettext-setup:
	-rm -f gp-gettext-setup.mk

all-local: all-local-gp-gettext-setup
.PHONY: all-local-gp-gettext-setup
all-local-gp-gettext-setup:
	@:
	@set -e; \
	MAKEVARS_FILE="$$(test -f 'po/Makevars' || echo '$(srcdir)/')po/Makevars"; \
	MAKEVARS_DOMAIN="$$($(SED) -n 's/^DOMAIN \{0,\}= \{0,\}//p' "$$MAKEVARS_FILE")"; \
	MAKE_TIME_DOMAIN="$(GETTEXT_PACKAGE_LIBGPHOTO2_PORT)"; \
	if test "x$$MAKEVARS_DOMAIN" = "x$$MAKE_TIME_DOMAIN"; then \
	     if $(AM_V_P); then printf "  %-8s %s\n" CHECK "Good: Matching gettext domain values ($${MAKE_TIME_DOMAIN})"; fi; \
	     true; \
	elif test "x$$USE_NLS" = xyes; then \
	     printf "  %-8s %s\n" CHECK "Error: Mismatching gettext domain values ($${MAKE_TIME_DOMAIN}) vs $${MAKEVARS_DOMAIN})"; \
	     false; \
	else \
	     printf "  %-8s %s\n" CHECK "Warning: Mismatching gettext domain values ($${MAKE_TIME_DOMAIN}) vs $${MAKEVARS_DOMAIN})"; \
	     true; \
	fi
